version: "3.7"

services:
    schemaspy:
        container_name: schemaspy
        build:
            context:    ${DOCKER_DIRECTORY}/docker/
            dockerfile: ${DOCKER_DIRECTORY}/docker/Dockerfile
        volumes:
            - ${DOCKER_DIRECTORY}/resources/:/schemaspy/resources/:rw
            - ${DOCKER_DIRECTORY}/export/:/schemaspy/export/:rw
            - ${DOCKER_DIRECTORY}/profiles/:/schemaspy/profiles/:rw
        network_mode:   host
        command:        >
                        java -jar "/schemaspy/resources/schemaspy-6.1.0.jar" \
                            -configFile ${CONFIG_FILE} \
                            -hq \
                            -debug



